name: CloudHammer Open Source
timezone: Asia/Shanghai
markdown: kramdown
highlight: null
permalink: /:title.html

exclude:
  - README.md

nav:
  - title: 首页
    link: "/"
  - title: 关于
    link: "/about/"
  - title: 项目
    link: "#"
  - title: 博客
    link: "#"
